### ISSUE TITLE
How work in progress is it?

### ISSUE THREAD

**Issue by crecord** [bakercp/ofxESCPOS#1]
This isn't really an "issue" I was just wondering if this is up and running? 

I am looking to do a sculptural project with an epson thermal printer and OF. How feasible is it to use OF with a thermal printer? Which printer would you recommend and how much can you customize what and how it prints?

**Comment by icq4ever** [comment]
as well as crecord, I also have question. is this addon working with raspberry pi?

of course I'll test on my raspberry pi. but sometimes addons which have dependencies with ofxIO are not compiles :$. anyway want to use this addons with this [kiosk thermal printer](https://dpfastprint.en.alibaba.com/product/60662532270-807792976/58mm_Kiosk_thermal_printer_bill_ticket_printer_for_vending_machine.html?spm=a2700.icbuShop.41413.34.47b8c900e9YPQr). in product page, they saids compatible with `EPSON M-T532AF/AP` printer. i guess it work. 

i already tested with [sparkfun thermal printer](https://www.sparkfun.com/products/10438) with `ofxThermalPrinter` addon. but I didn't test with `ofxESCPOS`.

**Comment by bakercp** [comment]
I just installed an installation with quite a few epson thermal printers using this addon. It works for me and should work for any printer that can receive serial ESCPOS data.
