### ISSUE TITLE
text is ok but image is not.

### ISSUE THREAD

**Issue by icq4ever** [bakercp/ofxESCPOS#10]
hi bakercp. I can printing text very well. 

![printtext](https://user-images.githubusercontent.com/530796/54065170-ebfc0800-425f-11e9-9007-a40444e10c36.jpg) 
sorry for blurring. my phone focusing not working.

but.. sadly. printing image is NOT!?!

first, file name is not correct. extension will be `jpeg` -> `jpg`
https://github.com/bakercp/ofxESCPOS/blob/158b561cdf9230d7c557532025eae8587aa68ced/example_printer_image/src/ofApp.cpp#L53

after fixing filename, it prints but instead of image, prints junk text. probably something wrong. 
![printimage](https://user-images.githubusercontent.com/530796/54065172-ef8f8f00-425f-11e9-8944-d69a2eb89818.jpg)
I'm investigating now..

**Comment by icq4ever** [comment]
by the way, [this](https://www.dropbox.com/s/izqqzddhatzov8r/DP-Q582P%20datasheet%201.pdf?dl=0) is the my printer's data sheet.

**Comment by icq4ever** [comment]
ahha. my printer using 2inch paper, which is 384 dots.
addons' default width was set as 576, which is 3inch paper.

https://github.com/bakercp/ofxESCPOS/blob/158b561cdf9230d7c557532025eae8587aa68ced/libs/ofxESCPOS/Commands/include/ofx/ESCPOS/Commands/DefaultBitImageCommands.h#L39


![imagebuthole](https://user-images.githubusercontent.com/530796/54065650-53698600-4267-11e9-8abc-20e9d0735bb3.jpg)

after fix this, I can see puppy on paper :)
although there's a white hole on his face, probably it's related with threshold or somethings.

**Comment by icq4ever** [comment]
load "grayscaled jpg" are working perfect! 

![happypuppy](https://user-images.githubusercontent.com/530796/54065745-75afd380-4268-11e9-974f-b1aa9068dd72.jpg)

I'll close issue.

**Comment by bakercp** [comment]
That's super exciting!  Nice work.  What was your fix?

**Comment by icq4ever** [comment]
change variable `printHeadWidth` to 384. and that's it.

https://github.com/bakercp/ofxESCPOS/blob/158b561cdf9230d7c557532025eae8587aa68ced/libs/ofxESCPOS/Commands/include/ofx/ESCPOS/Commands/DefaultBitImageCommands.h#L39

**Comment by bakercp** [comment]
Really great to know.  That would have probably taken me some time to figure out too :)  Thanks!

**Comment by icq4ever** [comment]
also, my printer support various international fonts(it's already inplement on this addon actually.). I'm not test/digging deeply yet. but while i have conversation with seller from printer factory, they'll gonna send me sone font setting app soon. whenever I figure out what/how it works, gonna add new  example hopefully :)

**Comment by icq4ever** [comment]
@bakercp +b
