### ISSUE TITLE
Epson TM-T20 USB not working

### ISSUE THREAD

**Issue by fedeblock** [bakercp/ofxESCPOS#6]
Hi Chris,

I was trying to compile the example and there´s an issue : 

<i>libc++abi.dylib: terminating with uncaught exception of type serial::IOException: IO Exception (2)</i>

I think it´s a problem with the port setup, but cannot find the device for the printer.

This is what i have from system_profiler SPUSBDataType : 

TM-T20:

```
              Product ID: 0x0e03
              Vendor ID: 0x04b8  (Seiko Epson Corp.)
              Version:  1.00
              Serial Number: 4d554c460861290000
              Speed: Up to 12 Mb/sec
              Manufacturer: EPSON
              Location ID: 0x1a121000 / 6
              Current Available (mA): 100
              Current Required (mA): 2
              1284 Device ID: MFG:EPSON;CMD:ESC/POS;MDL:TM-T20;CLS:PRINTER;DES:EPSON TM-T20;CID:EpsonTM00001002;
```

I´m running OSX 10.9.4, OF 0.8.1

Thanks for your contribution to the community!

**Comment by bakercp** [comment]
This addon sends the ESCPOS commands via RS232 serial. So, if you are connected as a USB printer, the standard Serial devices probably won't work.
