### ISSUE TITLE
ImageUtils - constant error

### ISSUE THREAD

**Issue by subongjeong** [bakercp/ofxESCPOS#7]
my system - ofx 0.9.3 / windows 10 / vs 2015

```
std::size_t numPixels = width * height; // 1 byte / pixel

float qErrors[numPixels];
std::fill(qErrors, qErrors + numPixels, 0.0);
```

has 'const' error : 'must have a constant value in the expression' (my vs language is Korean)

so,, it works for me ;)

```
float *qErrors;
qErrors = (float*)malloc(numPixels * sizeof(float));
std::fill(qErrors, qErrors + numPixels, 0.0);
```

**Comment by bakercp** [comment]
Is this still an issue on 0.10.+? If so please reopen.
