### ISSUE TITLE
Non-supported printer on Mac (working on CUPS, not visible to ofSerial)

### ISSUE THREAD

**Issue by autr** [bakercp/ofxESCPOS#8]
Hey there, I'm trying to get my thermal printer working sans-driver

Via CUPS I can get it to print fine like so;

`lpr -o raw -H localhost -P MyThermalPrinterOnCups MyTextFile.txt`

Or with a command line library ...

`png2pos -c -p  MyImage.png > MyTextFile.txt && lpr -o raw -H localhost -P MyThermalPrinterOnCups MyTextFile.txt`

Though the addon however I have only 

```
[notice ] ofSerial: [0] = cu.serial1
[notice ] ofSerial: [1] = tty.serial1
[notice ] ofSerial: [2] = cu.Bluetooth-Incoming-Port
[notice ] ofSerial: [3] = tty.Bluetooth-Incoming-Port

```
So I've tried both cu.serial1 and tty.serial1, and using the CUPS alias "Thermal_Printer_H58_Printer_USB" but no luck so far!

**Comment by bakercp** [comment]
It sounds like it isn't a serial printer.  How is it connected to the computer?

**Comment by autr** [comment]
Via the USB port

**Comment by bakercp** [comment]
Hm -- not sure.  I haven't tested this with thermal printers that connect directly via USB, I've only tested via raw RS232 -> USB.  I would try to figure out if it's possible to send ESCPOS commands to that printer via the USB connection.

**Comment by bakercp** [comment]
This is probably the same type of issue: https://github.com/bakercp/ofxESCPOS/issues/6
