### ISSUE TITLE
Unable to connect to the port

### ISSUE THREAD

**Issue by VisWong** [bakercp/ofxESCPOS#9]
The sample run successfully but the console shows these error. To my assumption, the latest OS(Mac OS Sierra/ Openframework 9.8) no longer support the port. Any one have the solution to fix this problem? 

[ error ] SerialDevice::setup: IO Exception (2): No such file or directory, file /Users/hoyin1994/Documents/of_v0.9.8_osx_release/addons/ofxSerial/libs/serial/src/impl/unix.cc, line 151.
[ error ] ofApp::setup: Unable to connect to: /dev/tty.usbmodem411

**Comment by bakercp** [comment]
If it printed successfully, then I'm not sure why you got these errors.  It looks like you tried to connect to a USB serial devices (looks like an arduino uno?).
